title: 我的项目
subtitle: 这里展示了我的一些个人项目和开源贡献

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: projects

categories:
  - name: 个人项目
    sites:
      - name: 个人导航站
        description: 一个简洁美观的个人导航页面
        url: "#"
      - name: Todo List
        description: 基于Vue3的待办事项管理器
        url: "#"
      - name: 个人博客
        description: 使用Hexo搭建的技术博客
        url: "#"
  - name: 开源贡献
    sites:
      - name: Project A
        description: 开源项目贡献
        url: "#"
      - name: Project B
        description: 开源项目贡献
        url: "#" 